var zhuanjia = [
    {
        "id": 1,
        "tname": "导师团队",
        "poster": "许宝林",
        "postTime": "2023-08-04",
        "isvalid": true,
        "professor": [
            {
                "id": null,
                "pname": "许宝林",
                "pos": "合肥",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "星核猎手，人有五名，代价有三个，而宝林是其中之一",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "王帅",
                "pos": "合肥",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "包皮切割专家，手起刀落，干净利落。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "谢磊磊",
                "pos": "合肥",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "迦南学院的看门人，实力达到了斗宗巅峰，可以踏空而行，恐怖如斯。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "李威远",
                "pos": "合肥",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "北大青鸟扛把子",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "顾大凯",
                "pos": "合肥",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "重金求子！！！重金求子！！！重金求子！！！重金求子！！！重金求子！！！重金求子！！！重金求子！！！重金求子！！！重金求子！！！",
                "tname": null,
                "coverimg": null
            }
        ]
    },
    {
        "id": 2,
        "tname": "美国专家",
        "poster": "许宝林",
        "postTime": "2023-08-07",
        "isvalid": true,
        "professor": [
            {
                "id": null,
                "pname": "Kristi Porter, M.Ed. 克里斯蒂·波特",
                "pos": "总部",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "克里斯蒂·波特 Kristi Porter, M.Ed.\r\n　　As a training specialist for STAR Autism Support, Kristi Porter provides professional development and on-site coaching for educators and parents on implementing evidence based practices for students with Autism. Kristi graduated from Texas Women’s University with a master’s degree in special education as an Educational Diagnostician. Kristi has served in many different capacities in special education in Utah, Wyoming, and Texas. She had the privilege of representing educators on the Wyoming Advisory Panel for Students with Disabilities while serving as Chair Elect. Kristi is passionate about professional development and has presented at the Texas Council for Exceptional Children Conference, Texas Region 11 Directors Meeting, and the National Council for Exceptional Children.",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "Joel·Arick 乔·艾瑞克",
                "pos": null,
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "乔·艾瑞克 Joel·Arick\r\nSTAR训练法创始人，资深教育者、研究员和培训师；\r\n\r\n美国波特兰大学的荣誉教授；\r\n\r\n30多年经自闭症领域教研经验，创立自闭症教学策略；\r\n\r\n著有《自闭症指南－为患有自闭症孩子学校教育体系》;\r\n\r\n亲自教授东方启音训练师STAR训练方法及评估系统，参与设计STAR训练室，评估学员、制定教学计划及追踪学员进度。\r\n\r\n2016年-至今，与东方启音合作开办东方启音STAR中心",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "Sheila·Magee 希拉·麦基",
                "pos": null,
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "希拉·麦基 Sheila·Magee\r\nSTAR训练法创始人，美国大学特殊教育公立学校教师；   \r\n\r\n30多年经自闭症领域教研经验，创立自闭症教学策略；\r\n\r\n拥有多年星级训练法课程技巧的经验，包括：行为分解训练法、关键反应训练、日常生活的教学等；\r\n\r\n亲自教授东方启音训练师STAR训练方法及评估系统，参与设计STAR训练室，评估学员、制定教学计划及追踪学员进度。\r\n\r\n2016年-至今，与东方启音合作开办东方启音STAR中心",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "Aimee Dearmon 艾梅•迪尔蒙",
                "pos": null,
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "艾梅•迪尔蒙 Aimee Dearmon\r\n\r\n\r\n理学硕士，认证行为分析师，言语语言病理学-临床能力证书\r\n\r\n美国言语病理学家(SLP)及认证行为分析师(BCBA)\r\n\r\n15年以上自闭症行业经验\r\n\r\n主要从事开展培训课程、构建培训场地、及培训训练师，以在美国各个州、各个地区及社区开展STAR及Links课程",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "Debbie Ware 黛比·韦尔",
                "pos": null,
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "黛比·韦尔 Debbie Ware\r\n是一名言语病理学家，为美国各大州学校提供教学咨询\r\n\r\n \r\n\r\n目前担任阿肯色州Outreach项目的咨询专家，作为团队成员在阿肯色州为老师和训练师提供临床实践咨询\r\n\r\n \r\n\r\n同时担任行为方法夏季培训（为期一周）的协调员，这个训练包括了STAR课程的示范、辅导和实操练习\r\n\r\n \r\n\r\n在此之前，黛比就职于加州圣地亚哥联合学区，接受了自闭症领域的大量培训并同时参与当地一个为期3年的多机构赠款项目。这个项目完成后，她参与了圣地亚哥联合学区第一家基于循证研究的STAR课程自闭症儿童学前班级的开办。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "Elizabeth Curtin 伊丽莎白·珂汀",
                "pos": null,
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "伊丽莎白·珂汀 Elizabeth Curtin\r\n美国伊利诺伊大学厄巴纳-香槟分校 特殊教育学士 教育政策、组织和领导硕士\r\n\r\n \r\n\r\n持有伊利诺伊行政管理执照\r\n\r\n \r\n\r\n有8年的自闭症和其他障碍群体学生工作经验，现在是一名培训专家，通过讲座和教室咨询提供相关培训\r\n\r\n \r\n\r\n曾在涉及学术、功能性日常技能、社区和职业等的不同场所，提供小学、初中和高中不同年龄的教学。作为一名任课老师，伊丽莎白教授STAR和Links课程，她所在的班级成为该地区的小学级别示范站点",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "Lisa Kemmerer, Ph.D., BCBA-D 丽莎. 凯默勒",
                "pos": null,
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "丽莎. 凯默勒 Lisa Kemmerer, Ph.D., BCBA-D\r\n美国爱荷华大学特殊教育博士，委员会认证行为分析师；\r\n\r\n20多年自闭症儿童工作经验；\r\n\r\n担任多所大学教授、爱荷华大学自闭症协调员、曾在儿童医院中心工作、爱荷华和弗吉尼亚学区的行为分析师、特殊教育老师和辅导师。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "Nilma Aviles Nilma Aviles",
                "pos": null,
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "Nilma Aviles Nilma Aviles\r\nSince 2011, Nilma has worked as a classroom teacher of children with autism, as well as those affected by a variety of other developmental disabilities. She is a graduate of the University of Puerto Rico, where she received a Bachelor of Education in Adapted and Elemental Physical Education. Nilma began working with STAR Autism Support as coach of the Puerto Rico Autism Project in February of 2015. As a coach in the project, she uses strategies and tools found in the STAR Program and Links Curriculum to support the implementation of evidenced-based strategies at multiple school sites throughout Puerto Rico.\r\n\r\n毕业于波多黎各大学，获得应用及基础运动教育学学士学位。自2011年起，Nilma从事面向自闭症以及其他发展障碍儿童教师工作。从2015年初开始担任SAS在波多黎各的项目Coach，在波多黎各多所学校指导基于循证策略的STAR体系和Links课程的实施。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "Tracy Uden M.Ed., BCBA 特雷西.乌登",
                "pos": null,
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "特雷西.乌登 Tracy Uden M.Ed., BCBA\r\n美国亚利桑那州立大学教育硕士，委员会认证分析师；\r\n\r\n数十年公共教育导师、自闭症专家；\r\n\r\n协同SAS（STAR自闭症机构），通过讲座和现场咨询提供了大量的培训。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "Cindy Cui 崔广利",
                "pos": "广州",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "崔广利 Cindy Cui\r\n东方启音创始人兼技术运营副总裁\r\n\r\n香港言语训练师协会附属会员；\r\n\r\n擅长各种言语障碍的发音、逻辑表达、心理行为评估及训练方案设计；\r\n\r\n2000年赴北京协和医科大学学习，2005年赴日本鸟取县米子医科大学学习言语训练，并取得言语及吞咽训练法证书；\r\n\r\n2009年后考取美国SRJ言语训练培训一级、二级、三级、四级证书；\r\n\r\n完成了美国STAR临床培训，并获得相应证书；\r\n\r\n在医学院、妇幼保健院从事心理及言语训练的教学、临床评估及训练26年。曾多次在全国各级医院及幼儿园开展言语训练培训讲座，长期在东方启音培训、评估及设计课程。\r\n\r\n2008年-至今，担任东方启音课程及技术研发导师",
                "tname": null,
                "coverimg": null
            }
        ]
    },
    {
        "id": 3,
        "tname": "中国香港专家",
        "poster": "许宝林",
        "postTime": "2023-08-09",
        "isvalid": true,
        "professor": [
            {
                "id": null,
                "pname": "- 麦悦心",
                "pos": null,
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "麦悦心 -\r\n香港大学言语及听觉科学荣誉理学士，香港言语训练师协会会员；\r\n\r\n获得香港大学专业机修学院证书、PROMPT（重建口腔运动发音的提示）证书、喂食训练课程证书；\r\n\r\n香港儿童口语（粤语）能力量表合资格测试员，获得口吃训练课程证书、利用口腔感观工具纠正特殊儿童障碍课程证书、社交思考课程证书；\r\n\r\n认可深层咽肌神经刺激法训练师，获得Beckman口腔肌肉训练证书。\r\n\r\n2008年-至今，担任东方启音培训导师",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "Patrick Ko 高展鹏",
                "pos": "广州",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "高展鹏 Patrick Ko\r\n香港大学言语及听觉科学系理学士；\r\n\r\n香港言语训练师协会会员，认可吞咽训练法训练师、认可身心语言程式学培训师，取得美国SRJ言语训练一级、二级及三级证书；\r\n\r\n曾任香港言语训练师协会会长、香港言语训练师协会外务秘书；\r\n\r\n长期在东方启音培训训练师、设计课程、评估个案、家长培训及撰写训练报告等。\r\n\r\n2008年-至今，担任东方启音启智及逻辑表达课程导师。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "Flora Kwok 郭丽芳",
                "pos": "广州",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "郭丽芳 Flora Kwok\r\n香港资深幼儿言语教育导师；\r\n\r\n曾获得游戏及游戏工作基础证书、儿童情绪社交发展证书、美国应用心理学家证书和音乐训练课程证书等专业资质；\r\n\r\n在香港有多年儿童智力及言语发展的临床经验；\r\n\r\n在东方启音工作7年来，主要负责评估、培训及启智课程研发，尤其擅长在启智、表达和社交行为等方面的针对性方案制定。\r\n\r\n2008年-至今，担任东方启音培训导师",
                "tname": null,
                "coverimg": null
            }
        ]
    },
    {
        "id": 4,
        "tname": "国内专家",
        "poster": "许宝林",
        "postTime": "2023-08-09",
        "isvalid": true,
        "professor": [
            {
                "id": null,
                "pname": "操明阳",
                "pos": "深圳",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "操明阳\r\n毕业于湖北黄石理工大学临床专业，从事训练工作近10年，接受香港社区言语训练中心的启智认知及逻辑表达培训，并获得相应证书。\r\n\r\n2009年后取得美国SRJ言语训练培训一级、二级证书。\r\n\r\n在东方启音有7年的言语训练经验，目前工作在东方启音深圳中心，主要负责言语训练的个案评估、训练，病例管理及员工、家长培训。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "宋然",
                "pos": "深圳",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "宋然\r\n多次接受香港社区言语训练中心的启智认知及逻辑表达培训，并获得相应证书。\r\n\r\n2011年后取得美国SRJ言语训练培训一级、二级证书。\r\n\r\n在东方启音有7年的言语训练经验，目前工作在东方启音深圳中心，主要负责言语训练的个案评估、训练、病例管理、家长培训。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "杨泽仪",
                "pos": "青岛",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "杨泽仪\r\n完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一级、二级证书。\r\n\r\n香港中文大学硕士，有儿童与青少年健康相关专业知识，有丰富的言语训练临床经验。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "张晓磊",
                "pos": "青岛",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "张晓磊\r\n\r\n\r\n言语服务专业，多次接受香港社区言语训练中心的启智认知及逻辑表达培训，并获得相应证书。\r\n\r\n2009年后取得美国SRJ言语训练培训一级、二级证书。\r\n\r\n在东方启音有7年的言语训练经验，目前工作在东方启音北京中心，主要负责言语训练的个案评估、训练，病例管理及员工、家长培训。",
                "tname": null,
                "coverimg": null
            }
        ]
    },
    {
        "id": 5,
        "tname": "国内训练师",
        "poster": "许宝林",
        "postTime": "2023-08-09",
        "isvalid": true,
        "professor": [
            {
                "id": null,
                "pname": "路宾",
                "pos": "苏州",
                "domain": "打飞机",
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "路宾\r\n完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一级证书，拥护“用爱协助孩子成长”的理念",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "冯媛园",
                "pos": "成都",
                "domain": "大大大",
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "冯媛园\r\n言语训练专业\r\n\r\n完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一、二级证书，持有国家认证二级心理咨询师证，有多年的言语训练临床经验。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "徐振雪",
                "pos": "福州",
                "domain": "气功",
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "徐振雪\r\n · 毕业于湖北理工学院护理学专业；\r\n\r\n · 有丰富的儿童护理临床经验及优秀引导经验；\r\n\r\n · 获得SRJ及认知、STAR课程等专业培训证书；\r\n\r\n · 在东方启音有多年的言语治疗临川经验，主要负责言语治疗评估、治疗、病历管理、家长培训；\r\n\r\n · 擅长儿童的综合评估以及课程规划，对儿童的发音引导、逻辑表达，游戏技巧提升有较丰富的经验。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "王兰娇",
                "pos": "北京",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "王兰娇\r\n完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一级、二级证书。有多年的言语训练临床经验。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "于真顺",
                "pos": "北京",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "于真顺\r\n言语训练专业\r\n\r\n完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一级证书，大学修特殊教育学专业，拥有特殊教育资格证有特殊教育临床经验，教学方式灵活多变，富有感染力。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "林敬",
                "pos": "北京",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "林敬\r\n言语训练专业，多次接受香港社区言语训练中心的启智认知及逻辑表达培训，并获得相应证书。\r\n\r\n2011年后取得美国SRJ言语训练培训一级、二级证书。在东方启音有4年的言语训练经验，目前工作在东方启音深圳中心，主要负责言语训练的个案评估、训练，病例管理及员工、家长培训。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "牛芷平",
                "pos": "上海",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "牛芷平\r\n言语训练专业，多次接受香港社区言语训练中心的启智认知及逻辑表达培训，并获得相应证书。\r\n\r\n2009年后取得美国SRJ言语训练培训一级、二级证书。\r\n\r\n在东方启音有6年的言语训练经验，目前工作在东方启音上海中心，主要负责言语训练的个案评估、训练，病例管理及员工、家长培训。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "向娟",
                "pos": "上海",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "向娟\r\n完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一级、二级证书。有多年的言语训练临床经验。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "吴洁坡",
                "pos": "上海",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "吴洁坡\r\n毕业于韩山师范学院，多年从事幼儿教育，以启智认知和社交行为课程开发、教学及培训工作为主。\r\n\r\n曾从事儿童言语、智能开发、心理发展教育与研究，并有丰富的言语训练临床经验。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "毛梓华",
                "pos": "上海",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "毛梓华\r\n毕业于美国马凯特大学儿童心理训练研究生专业，擅长儿童言语行为课程，感统课程和注意力训练。\r\n\r\n完成香港启智认知及逻辑表达培训、美国SRJ言语训练培训一级、二级证书，有多年的言语训练临床经验。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "陈璐",
                "pos": "上海",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "陈璐\r\n言语训练专业，多次接受香港社区言语训练中心的启智认知及逻辑表达培训，并获得相应证书。\r\n\r\n2009年后取得美国SRJ言语训练培训一级、二级证书。\r\n\r\n在东方启音有6年的言语训练经验，目前工作在东方启音上海中心，主要负责言语训练的个案评估、训练，病例管理及员工、家长培训。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "刘彦",
                "pos": "武汉",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "刘彦\r\n完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一级、二级证书。有多年的言语训练临床经验。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "陈雅琴",
                "pos": "武汉",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "陈雅琴\r\n毕业于言语训练专业，从事言语训练工作近7年；\r\n\r\n完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一级、二级证书，有丰富的言语训练临床经验。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "钱文",
                "pos": "武汉",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "钱文\r\n华中师范大学心理硕士，持有国家心理咨询师二级证书；\r\n\r\n完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一级、二级证书； 有儿童与青少年心理健康方面的专业知识，有丰富的言语训练临床经验。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "崔艳",
                "pos": "武汉",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "崔艳\r\n毕业于语言学专业，有多年汉语语言教学经验，善于在游戏互动中教学，寓教于乐；\r\n\r\n完成香港启智认知、逻辑表达培训及STAR Program的专项培训；\r\n\r\n美国言语训练培训一级、二级证书，有丰富的言语训练临床经验。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "胡诗敏",
                "pos": "长沙",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "胡诗敏\r\n毕业于长沙民政职业技术学院训练服务技术专业\r\n\r\n完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一级、二级证书，有丰富的言语训练临床经验。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "袁钰珂",
                "pos": "长沙",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "袁钰珂\r\n毕业于湖南中医药大学湘杏学院心理学专业\r\n\r\n完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一级、二级证书，有丰富的言语训练临床经验。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "刘定潘",
                "pos": "长沙",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "刘定潘\r\n完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一级、二级证书，有丰富的言语训练临床经验。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "彭鹏",
                "pos": "长沙",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "彭鹏\r\n 毕业于陕西中医药大学应用心理学（医学方向），完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一级、二级证书，并完成了美国STAR临床课程，获得相应证书。曾在湖南省残疾人康复研究中心工作多年，有丰富的言语训练和心理咨询临床经验。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "彭道馨",
                "pos": "长沙",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "彭道馨\r\n毕业于长沙民政职业技术学院，曾在株洲市康复医院儿童康复科工作工作两年余，完成香港启智认知及逻辑表达培训，美国言语训练培训一级、二级证书，完成了美国STAR临床课程，并获得相应证书。掌握扎实的儿童与青少年发育康复相关专业知识，有多年丰富的言语训练临床经验。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "王本成",
                "pos": "长沙",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "王本成\r\n\r\n毕业于中国医科大学；完成香港启智认知、逻辑表达及美国STAR课程培训，并获得相关证书；取得美国言语训练培训一级，二级证书。\r\n\r\n擅长各类儿童言语障碍、专注力及多感官训练，具有丰富的临床个案训练与评估经验。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "李怡然",
                "pos": "南京",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "李怡然\r\n毕业于南京特教学院自闭症儿童康复专业。完成香港启智认知及逻辑表达培训；美国SRJ口部肌肉训练培训一级、二级证书，有丰富的言语治疗临床经验及技巧，擅于将课程目标与游戏结合；完成了美国STAR临床课程，并获得相应证书。教学活泼轻松，目标张弛有度，让孩子在笑声中获得多项智能发展。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "周露",
                "pos": "南京",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "周露\r\n毕业于安徽皖南医学院临床医学专业，并取得国家营养师资格。完成香港启智认知及逻辑表达培训，美国SRJ口部肌肉训练培训一级、二级证书；完成了美国STAR临床课程，并获得相应证书。对儿童教育及临床评估有丰富的经验与技巧，富有亲和力，善于抓住孩子的内心。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "程理论",
                "pos": "重庆",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "程理论\r\n完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一级证书，拥护“用爱协助孩子成长”的理念",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "漆柔显",
                "pos": "重庆",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "漆柔显\r\n毕业于重庆师范大学，曾在台湾接受儿童奥尔夫音乐教育培训2b-4m所有课程，并通过考核。\r\n\r\n从事言语教育3年，对儿童的互动社交，语言表达，游戏技巧有丰富的经验。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "刘盈盈",
                "pos": "重庆",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "刘盈盈\r\n毕业于南京特殊教育师范学院美术教育专业，完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一级、二级证书，有丰富的言语训练临床经验，了解儿童心理发展，擅长处理儿童身心发展问题。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "裴慧娟",
                "pos": "重庆",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "裴慧娟\r\n毕业于天津体育学院运动训练专业。完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一级、二级证书，有丰富的言语训练临床经验，了解儿童心理发展，擅长进行脑瘫儿童的训练服务。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "彭裕良",
                "pos": "广州",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "彭裕良\r\n完成香港启智认知及逻辑表达培训，获美国SRJ言语训练培训一、二级证书。，有两年多的言语训练临床经验。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "吕世康",
                "pos": "广州",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "吕世康\r\n毕业于中山大学心理系，在儿童心理学和互动表达方面有丰富的专业知识和经验。\r\n\r\n完成香港启智认知及逻辑表达培训，美国SRJ口部肌肉训练培训一级、二级证书。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "唐亚玲",
                "pos": "深圳",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "唐亚玲\r\n言语训练专业，多次接受香港社区言语训练中心的启智认知及逻辑表达培训，并获得相应证书。\r\n\r\n2011年后取得美国SRJ言语训练培训一级、二级证书。在东方启音有4年的言语训练经验，目前工作在东方启音深圳中心，主要负责言语训练的个案评估、训练，病例管理及员工、家长培训。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "曾少南",
                "pos": "深圳",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "曾少南\r\n\r\n\r\n完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一级、二级证书，有丰富的言语训练临床经验。\r\n\r\n专注于互动与表达等有关方面的实践与探索，为有需要的人士提供优质的多感官训练。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "董春艳",
                "pos": "深圳",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "董春艳\r\n完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一级证书，拥护“用爱协助孩子成长”的理念",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "吴璇",
                "pos": "深圳",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "吴璇\r\n应用心理学硕士，持有二级心理咨询师证，在促进儿童心理及家长成长方面积累了丰富的实践经验，擅长处理言语、行为、情绪、多动、注意力不集中、人际交往等各类儿童发展问题。\r\n\r\n完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一级、二级证书，累积发育迟缓、自闭症、脑瘫、唐氏综合症及其他特殊儿童言语病例数百例。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "张志腾",
                "pos": "深圳",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "张志腾\r\n完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一级证书，拥护“用爱协助孩子成长”的理念",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "温玉龙",
                "pos": "东莞",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "温玉龙\r\n毕业于中山医科大学，曾在中山医科大学附属医院完成相应临床实习，擅长儿童与青少年健康发展领域的研究。\r\n\r\n完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一级、二级证书，有训练卫生系统以及丰富的言语训练临床经验，累积发育迟缓、自闭症、脑瘫、唐氏综合症及其他特殊儿童病例数百例。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "欧阳晶",
                "pos": "东莞",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "欧阳晶\r\n完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一级、二级证书，有丰富的言语训练临床经验。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "邵伟荣",
                "pos": "东莞",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "邵伟荣\r\n毕业于广东医科大学护理学专业，在三甲医院有儿童护理经验。 多次接受香港社区言语治疗中心的启智认知及逻辑表达培训，取得美国SRJ口部肌肉训练一、二级证书；接受美国自闭症权威机构STAR Autism Support(SAS)培训，擅于儿童运动发展功能性训练、巧用游戏教学法提高儿童言语表达。完成了美国STAR一级课程，并获得相应证书。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "杨婷婷",
                "pos": "杭州",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "杨婷婷\r\n　　毕业于嘉兴学院汉语国际教育专业，完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一级证书，有儿童与青少年健康相关专业知识，有丰富的言语训练和心理咨询临床经验。完成了美国STAR一级课程，并获得相应证书。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "武婷婷",
                "pos": "杭州",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "武婷婷\r\n　　毕业于延边大学英语语言文学专业，完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一级证书，有儿童与青少年健康相关专业知识，有丰富的言语训练和心理咨询临床经验。完成了美国STAR一级课程，并获得相应证书。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "郑宏娟",
                "pos": "杭州",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "郑宏娟\r\n　　完成香港启智认知及逻辑表达培训，美国SRJ言语训练培训一级、二级证书，有丰富的言语服务临床经验。",
                "tname": null,
                "coverimg": null
            }
        ]
    },
    {
        "id": 6,
        "tname": "澳大利亚专家",
        "poster": "许宝林",
        "postTime": "2023-08-09",
        "isvalid": true,
        "professor": [
            {
                "id": null,
                "pname": "Kerry Watson 克里•沃森",
                "pos": "总部",
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "克里•沃森 Kerry Watson\r\n自2012年以来，克里直接参与了一系列发育障碍的儿童和成年人的服务与训练。她有着多种角色，包括担任直接援助工作者，以及在公共教育系统中教导智力障碍和自闭症谱系障碍的学生。 \r\n\r\n克里在她的课堂上教授Links课程，并在加入STAR Autism Support之前，曾在澳大利亚维多利亚州作为培训专家援助ABA试点项目，并获得了执教认证。克里喜欢融入社区，并热爱她的工作—指导教师和员工教授STAR和Links课程，采取循证策略，支持这一理念，并为创造可持续的社会变革做出贡献。\r\n\r\n克里拥有皇家墨尔本理工大学教育与应用科学（障碍）双学位，目前正在莫纳什大学攻读应用行为分析教育硕士学位。",
                "tname": null,
                "coverimg": null
            },
            {
                "id": null,
                "pname": "Sally Hewat 莎莉",
                "pos": null,
                "domain": null,
                "poster": null,
                "postTime": null,
                "isvalid": null,
                "ptype": null,
                "intro": "莎莉 Sally Hewat\r\n澳大利亚纽卡斯尔大学言语病理学系院长；\r\n\r\nSally Hewat教授曾与澳大利亚Trinh基金会合作，共同为越南大学建立言语训练院系，并获得由胡志明市人民委员会颁发的奖章，以此感谢她为越南言语训练领域的卓越贡献。\r\n\r\n2015年-至今，Sally Hewat带领澳大利亚纽卡斯尔大学Newcastle言语病理学系毕业生到东方启音全国各中心实习，推动中国国内言语训练行业发展。",
                "tname": null,
                "coverimg": null
            }
        ]
    }
]
